version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/ProjectNext-intervenants
      - /node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm run dev"

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  db_data:
