version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    image: node:18
    working_dir: /my-app
    volumes:
      - .:/my-app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "8080:80"

volumes:
  db_data:
